#设置公用内容
server:
  port: 9090
spring:
  application:
    name: ePlus
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://111.229.160.175:1433;DatabaseName=eplus
    username: sa
    password: Eplus123!
    # hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      #最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒。
      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      #连接测试查询
      connection-test-query: SELECT 1
  #异常时触发事务回滚
  transaction:
    rollback-on-commit-failure: true
  #设置Spring AOP代理方式：true-cglib代理；false-jdk*屏蔽的关键字*
  aop:
    proxy-target-class: true

  #统一时间返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #返回时间戳时不进行格式化
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false #是否返回时间戳
  #thymeleaf start
  thymeleaf:
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    suffix: .html

#mapper 别名扫描
mybatis:
  type-aliases-package: com.ep.model.model
  #mapper.xml文件位置
  mapper-locations: classpath:mappers/*.xml
  #数据库类型
  configuration.database-id: mysql
  #自动驼峰转换
  configuration.map-underscore-to-camel-case: true
#pagehelper  分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql